# 29일차

## 신경망

### 연습문제
아래는 신경망의 출력값이다. 소프트맥스를 이용해 확률값으로 변환하시오.
- [1,0,1]
- [1,2,3]
- [10,20,30]
- [101,102,103]
- [[10,5,0],[-3,-2,-1],[0,0,1]]

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pred_y=np.array([101,102,103])
np.exp(pred_y)/np.exp(pred_y).sum()

array([0.09003057, 0.24472847, 0.66524096])

In [3]:
np.exp(2)/np.exp(1)

2.7182818284590455

In [4]:
np.exp(101)/np.exp(100)

2.718281828459045

In [5]:
pred_y=np.array([10,20,30])
np.exp(pred_y)/np.exp(pred_y).sum()

array([2.06106005e-09, 4.53978686e-05, 9.99954600e-01])

In [6]:
pred_y=np.array([[10,5,0],[-3,-2,-1],[0,0,1]])

In [7]:
(np.exp(pred_y)/(np.exp(pred_y).sum(axis=1).reshape(3,1))).round(3)

array([[0.993, 0.007, 0.   ],
       [0.09 , 0.245, 0.665],
       [0.212, 0.212, 0.576]])

## 텐서플로 기초

In [11]:
import tensorflow as tf
tf.__version__

'2.4.0'

In [12]:
from tensorflow import keras

In [14]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 7286237772201206373]

### 상수

In [15]:
a=tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
a.numpy()

3

In [17]:
a=tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [18]:
a.numpy()

array([1, 2, 3])