# 33일차

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as ply

In [3]:
np.random.seed(2021)
img=np.random.rand(6,6).round(1)
img

array([[0.6, 0.7, 0.1, 0.3, 1. , 0.1],
       [0.2, 0.8, 0.7, 0.8, 0.1, 0.1],
       [1. , 0.6, 0.1, 0.6, 0.6, 1. ],
       [0.6, 0.4, 0.5, 0.2, 0.6, 0.2],
       [0.6, 0.5, 0.5, 0.8, 0.7, 0.1],
       [0.7, 0.6, 0.8, 0.2, 0.6, 0.6]])

In [4]:
filter=np.array([[1,0,1],[0,-4,0],[1,0,1]])

### 연습문제
- img 에 filter로 convolution 적용한 후,2x2 맥스풀링을 적용하시오.
- convolution 결과에 relu 활성화 함수를 적용하면 어떻게 변할까

In [5]:
result=[]

for i in range(4):
    l=[]
    for j in range(4):
        l.append((img[i:i+3,j:j+3]*filter).sum())
    result.append(l)
    
np.array(result).round(2)

array([[-1.4, -0.6, -1.4,  1.6],
       [-0.4,  1.8, -0.5, -1.1],
       [ 0.6,  0.5,  1.1,  0.1],
       [ 0.6, -0.6, -0.7, -1.6]])

In [6]:
result2=np.array(result).copy()
result2[result2<0]=0
result2

array([[0. , 0. , 0. , 1.6],
       [0. , 1.8, 0. , 0. ],
       [0.6, 0.5, 1.1, 0.1],
       [0.6, 0. , 0. , 0. ]])